export const tweetsData = [   
    {
        handle: `@IloveHanni24 💎`,
        profilePic: `images/danielle1.jpeg`,
        likes: 5021,
        retweets: 10,
        tweetText: `hey guys I am new to the X / Twitter thing, but I just started using it just to follow Newjeans stuff.`,
        tweetImage: 'images/post1.jpg',
        replies: [{
            handle: `@randomkid1`,
            profilePic: `images/haerin1.jpeg`,
            tweetText: `Check this gif out XD`,
            tweetGif: `images/hannii.gif`,
        },{
            handle: `@randomkid2 ✅`,
            profilePic: `images/haerin2.jpeg`,
            tweetText: `Hey I went to their concert last year `,
        },{
            handle: `@randomkid3 ✅`,
            profilePic: `images/haerin1.jpeg`,
            tweetText: `hey @randomkid1 our profile pic looks the same LOLOLOLOL`,
        },],
        isLiked: false,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-8562944223e1',
    },    
    {
        handle: `kittyrin 💕`,
        profilePic: `images/danielle2.jpg`,
        likes: 2110,
        retweets: 234,
        isLiked: false,
        isRetweeted: false,
        tweetText: `I need volunteers for a one-way mission to Mars 🪐. No experience necessary🚀Watch here: https://www.youtube.com/watch?v=11cta61wi0g`,
        tweetImage: 'images/imageatag.jpg', 
        tweetImageLink : 'https://www.youtube.com/watch?v=11cta61wi0g',
        replies: [
                  {
                handle: `@randomkid4`,
                profilePic: `images/haerin1.jpeg`,
                tweetText: `OMGG!!!`,
            },
                  {
                handle: `@randomkid5✅`,
                profilePic: `images/haerin2.jpeg`,
                tweetText: `Just saw this mv, it was fire 🔥🔥🔥🔥`,
            },
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: '3c23454ee-c0f5-9g9g-9c4b-77835tgs8',
    },
        {
        handle: `miudolli`,
        profilePic: `images/hanni1.jpg`,
        likes: 10,
        retweets: 3,
        tweetText: `Bro ☠️☠️☠️☠️`,
        tweetVideo: 'images/video1.mp4', 
        replies: [
            {
                handle: `@lovhrin 💞`,
                profilePic: `images/hanni2.jpg`,
                tweetText: `Brah, what's with this generations humor.`,
                tweetGif : `images/deadreaction.gif`
            },
            {
                handle: `@dollhae`,
                profilePic: `images/hyein.jpg`,
                tweetText: `XDDDDDDDD ☠️☠️`,
            },
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: '8hy671sff-c0f5-4545-9c4b-1237gyys4e',
    },     
    {
        handle: `@nwjshae`,
        profilePic: `images/elonmusk.jpg`,
        likes: 1213,
        retweets: 3,
        tweetText: `A look back at Elon Musk's first year owning Twitter, in tweets | CNN Business`,
        tweetImage: 'images/elonmuskpost.jpg', 
        tweetImageLink :'//edition.cnn.com/2023/10/28/tech/elon-musk-year-owning-twitter-in-tweets/index.html',
        replies: [
            {
                handle: `@elomuskjejeje`,
                profilePic: `images/elonmusk2.jpeg`,
                tweetText: `I like Mark Soccerberg.`,
            },
            {
                handle: `@haeooki`,
                profilePic: `images/elonmusk3.jpeg`,
                tweetText: `Hey guys want to join my site? Click the link below 👇`,
            },
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: '8hy671sff-c0f5-4545-9c4b-1237gyys45',
    },    {
        handle: `@TrollBot66756542 💎`,
        profilePic: `images/troll.jpeg`,
        likes: 5,
        retweets: 3,
        tweetText: `1Trillion IQ Indeed, btw do you like it @Dumkin? #galaxybrainmeme #dumb #dumbkin #meme #fyp シ゚viral`,
        tweetVideo: 'images/video2.mp4', 
        replies: [
            {
                handle: `@minecraftkid`,
                profilePic: `images/minecraft.jpeg`,
                tweetText: `I really love this videos, make my brain go rot more.`,
                
            },
            {
                handle: `@Ilovetomato`,
                profilePic: `images/minecraft1.jpeg`,
                tweetText: `Woah, time to try this in real geym. Skibidi pap yes yes`,
                tweetGif: `images/brainrot.gif`,
            },
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: '8hy671sff-c0f5-4545-9c4b-1237gyys43',
    },    
    {
        handle: `notkennut`,
        profilePic: `images/mypic.jpg`,
        likes: 0,
        retweets: 0,
        tweetText: `If you reached this area why don't you follow my gihub :). Also check my last week project 👀👇`,
        tweetImage: 'images/screenshot.png', 
        tweetImageLink : 'https://github.com/KenthJy/ACER-PH_ClONE',
        replies: [],
        isLiked: false,
        isRetweeted: false,
        uuid: '8hy671sff-c0f5-4545-9c4b-1237gyys42',
    },    
    
]